# fly.toml app configuration file generated for voice-ws-purple-leaf-194 on 2025-10-07T21:17:39-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'voice-ws-purple-leaf-194'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "off"   # keep it always-on
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb"   # 256–512mb is plenty for this WS
